repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy-fastapi
        name: mypy (fastapi_app)
        entry: cmd /c "cd fastapi_app && uv run mypy src/"
        language: system
        pass_filenames: false
        types: [python]
        require_serial: true
      - id: mypy-flask
        name: mypy (flask_app)
        entry: cmd /c "cd flask_app && uv run mypy src/"
        language: system
        pass_filenames: false
        types: [python]
        require_serial: true

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
        stages: [commit-msg]